- hosts: localhost
  vars_files:
    - /Users/{{ YOUR_USER }} /secrets/secret.yml
  tasks:
    - name: Print export commands for the current shell
      debug:
        msg: |
          export SAMPLE="{{ secret.SAMPLE }}"
